#
# Continuous Integration (CI) Pipeline
#

trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
- master
- release/*
- feature/*

variables:
  buildConfiguration: 'Release'

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_solution
    displayName: Build Solution
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.302
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: clog.sln/clog.sln
        arguments: --configuration $(buildConfiguration)
    - publish: $(System.DefaultWorkingDirectory)/nupkg
      artifact: ToolNuPkg
    - script: |
        dotnet tool install --global --add-source $(System.DefaultWorkingDirectory)/nupkg Microsoft.Logging.CLOG
        mkdir build
        cd build
        export CLOG_DEVELOPMENT_MODE=1
        cmake ../examples
        make
      displayName: Test Sample Build
