#
# Continuous Integration (CI) Pipeline
#

trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
- master
- release/*
- feature/*

variables:
  buildConfiguration: 'Release'

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_solution
    displayName: Build Solution
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.302
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: clog.sln/clog.sln
        arguments: --configuration $(buildConfiguration)
    - publish: $(System.DefaultWorkingDirectory)/nupkg
      artifact: ToolNuPkg
- stage: Test
  displayName: Test
  dependsOn:
  - build
  jobs:
  - job: test_linux
    displayName: Test Linux
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.302
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DownloadBuildArtifacts@0
      displayName: Download Build Artifacts
      inputs:
        artifactName: ToolNuPkg
        downloadPath: $(System.DefaultWorkingDirectory)/nupkg
    - script: |
        ls $(System.DefaultWorkingDirectory)/nupkg
        dotnet tool install --global --add-source $(System.DefaultWorkingDirectory)/nupkg Microsoft.Logging.CLOG
        mkdir build
        clog --installDirectory build/clog
        cd build
        export CLOG_DEVELOPMENT_MODE=1
        cmake ../examples
        cmake --build .
      displayName: Test Sample Build
  - job: test_windows
    displayName: Test Windows
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Build Artifacts
      inputs:
        artifactName: ToolNuPkg
        downloadPath: $(System.DefaultWorkingDirectory)/nupkg
    - pwsh: |
        dotnet tool install --global --add-source $(System.DefaultWorkingDirectory)/nupkg Microsoft.Logging.CLOG
        mkdir build
        clog --installDirectory build/clog
        cd build
        $env:CLOG_DEVELOPMENT_MODE = 1
        cmake ../examples
        cmake --build .
      displayName: Test Sample Build
  - job: test_macos
    displayName: Test macOS
    pool:
      vmImage: macOS-latest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.302
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DownloadBuildArtifacts@0
      displayName: Download Build Artifacts
      inputs:
        artifactName: ToolNuPkg
        downloadPath: $(System.DefaultWorkingDirectory)/nupkg
    - pwsh: |
        dotnet tool install --global --add-source $(System.DefaultWorkingDirectory)/nupkg Microsoft.Logging.CLOG
        mkdir build
        clog --installDirectory build/clog
        cd build
        $env:CLOG_DEVELOPMENT_MODE = 1
        cmake ../examples
        cmake --build .
      displayName: Test Sample Build

