#
# Continuous Integration (CI) Pipeline
#

trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
- master
- release/*
- feature/*

variables:
  buildConfiguration: 'Release'

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_solution
    displayName: Build Solution
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: clog.sln/clog.sln
        arguments: --configuration $(buildConfiguration)
    - publish: $(System.DefaultWorkingDirectory)/nupkg
      artifact: ToolNuPkg
